"""Reporter: turn scorecards into a findings document (markdown + JSON).

No composite leaderboard, by design (design doc §5) — one scorecard per
(candidate, doc_type, locale). The confidently-wrong rate leads, because the
whole thesis rides on it.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .score import Scorecard


def write_reports(cards: list[Scorecard], out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "scorecards.json"
    md_path = out_dir / "findings.md"

    json_path.write_text(json.dumps([_card_json(c) for c in cards], indent=2))
    md_path.write_text(_markdown(cards))
    return md_path, json_path


def _card_json(c: Scorecard) -> dict:
    d = asdict(c)
    d["calibration"] = [
        {"stated": round(b.stated, 2), "actual": round(b.actual, 4), "n": b.n}
        for b in c.calibration
    ]
    return d


def _markdown(cards: list[Scorecard]) -> str:
    lines = [
        "# Benchmark Findings",
        "",
        "_Generated by viva-bench. Scorecards per (model × document type × locale)._",
        "_No composite score — a model that is best on average can still be the one",
        "that is occasionally, confidently, catastrophically wrong._",
        "",
        "## The ruin metric first: confidently-wrong rate",
        "",
        "How often the pipeline accepts a value that is actually false. The product",
        "promise rides on this being ~0. Everything else is economics.",
        "",
        "| candidate | doc_type | locale | confidently-wrong | verified-coverage |",
        "|---|---|---|---|---|",
    ]
    for c in sorted(cards, key=lambda x: (-x.system_confidently_wrong, x.candidate)):
        lines.append(
            f"| {c.candidate} | {c.doc_type} | {c.locale} | "
            f"{c.system_confidently_wrong:.1%} | {c.system_verified_coverage:.1%} |"
        )

    lines += ["", "## Raw model quality", "",
              "| candidate | doc_type | locale | runs | parse-fail | accuracy | recall | strict | self-consist | ECE |",
              "|---|---|---|---|---|---|---|---|---|---|"]
    for c in sorted(cards, key=lambda x: (x.candidate, x.doc_type, x.locale)):
        ece = f"{c.ece:.3f}" if c.ece is not None else "n/a"
        lines.append(
            f"| {c.candidate} | {c.doc_type} | {c.locale} | {c.n_runs} | "
            f"{c.n_parse_fail} | {c.accuracy:.1%} | {c.recall:.1%} | "
            f"{c.strict_rate:.1%} | {c.self_consistency:.1%} | {ece} |"
        )

    lines += ["", "## Calibration detail (are stated confidences meaningful?)", ""]
    for c in cards:
        if c.ece is None:
            continue
        lines.append(f"### {c.candidate} · {c.doc_type} · {c.locale} (ECE {c.ece:.3f})")
        lines.append("")
        lines.append("| stated confidence | actual accuracy | n |")
        lines.append("|---|---|---|")
        for b in c.calibration:
            if b.n:
                lines.append(f"| {b.stated:.0%} | {b.actual:.0%} | {b.n} |")
        lines.append("")

    lines += [
        "## How to read this",
        "",
        "- **ECE** (expected calibration error): 0 means stated confidence matches",
        "  reality; high means the model's self-reported confidence is noise —",
        "  which is exactly why OrionViva constructs confidence by verification",
        "  rather than trusting the model (see docs/extraction-and-confidence.md).",
        "- **recall** below 100% means the model silently dropped claims — the",
        "  failure mode a balances-only benchmark would hide.",
        "- **self-consistency** below 100% means repeat runs disagree — the signal",
        "  N-sampling exists to exploit.",
        "",
        "_This document is committed to the build log even where it embarrasses the",
        "project's assumptions. That is the point._",
    ]
    return "\n".join(lines) + "\n"
